import React from 'react'
import {ColorSwatch,Pill,PrimaryButton,GhostButton,ItemRow} from '../components/ui.jsx'
export const OCCASIONS=['Casual','College','Office','Date','Party','Wedding','Formal','Travel']
export function ProfileScreen({profile,photoUrl,onContinue}) {
 return <div><div className="flex items-center gap-3 mb-6"><img src={photoUrl} alt="You" className="w-14 h-14 rounded-2xl object-cover border border-stone-300"/><div><p className="font-display text-xl">Here's what I see</p><p className="text-xs text-stone-400">Styling read, not a medical one</p></div></div>
 <div className="rounded-3xl bg-white border border-stone-200 p-5 mb-4"><p className="text-sm text-stone-700 leading-relaxed">{profile.summary}</p></div>
 <div className="grid grid-cols-2 gap-3 mb-4"><InfoCard label="Face shape" value={profile.faceShape} sub={profile.faceShapeConfidence ? Math.round(profile.faceShapeConfidence*100)+'% confidence':null}/><InfoCard label="Undertone" value={profile.skinToneUndertone}/><InfoCard label="Hair" value={profile.hairstyle} span/><InfoCard label="Current style" value={profile.existingStyle} span/></div>
 {profile.proportions&&<div className="rounded-2xl border border-stone-200 p-4 mb-4"><p className="text-xs text-stone-400 mb-1">Proportions</p><p className="text-sm text-stone-700">{profile.proportions}</p></div>}
 {profile.bestColors?.length>0&&<div className="mb-8"><p className="text-xs text-stone-400 mb-2">Colors that work well on you</p><div className="flex flex-wrap gap-2">{profile.bestColors.map(c=><ColorSwatch key={c} name={c}/>)}</div></div>}
 <PrimaryButton className="w-full" onClick={onContinue}>Continue</PrimaryButton></div>
}
function InfoCard({label,value,sub,span}) { return <div className={'rounded-2xl border border-stone-200 p-4 '+(span?'col-span-2':'')}><p className="text-xs text-stone-400 mb-1">{label}</p><p className="text-sm text-stone-800 capitalize">{value}</p>{sub&&<p className="text-[11px] text-stone-400 mt-0.5">{sub}</p>}</div> }
export function OccasionScreen({occasion,customOccasion,setCustomOccasion,onPick,onGenerate,error}) { return <div><p className="text-stone-500 text-sm mb-6">What are you dressing for?</p><div className="flex flex-wrap gap-2 mb-4">{OCCASIONS.map(o=><Pill key={o} selected={occasion===o} onClick={()=>onPick(o)}>{o}</Pill>)}<Pill selected={occasion==='Custom'} onClick={()=>onPick('Custom')}>Custom</Pill></div>{occasion==='Custom'&&<input className="w-full rounded-2xl border border-stone-300 bg-white px-4 py-3 text-sm mb-4" placeholder="Describe the occasion…" value={customOccasion} onChange={e=>setCustomOccasion(e.target.value)}/>} {error&&<p className="text-sm text-red-700 mb-4">{error}</p>}<PrimaryButton className="w-full mt-4" disabled={!occasion||(occasion==='Custom'&&!customOccasion.trim())} onClick={onGenerate}>Generate outfits</PrimaryButton></div> }
export function ResultsScreen({data,occasion,onSelect,onAnother}) { return <div><p className="text-stone-500 text-sm mb-6">3 looks for <span className="text-stone-800">{occasion}</span></p><div className="space-y-4 mb-6">{data.outfits?.map((o,i)=><button key={i} onClick={()=>onSelect(o)} className="w-full text-left rounded-3xl border border-stone-200 bg-white p-5 hover:border-emerald-400 transition-colors"><p className="text-xs text-emerald-700 mb-1">Look {String(i+1).padStart(2,'0')}</p><p className="font-display text-xl mb-2">{o.title}</p><p className="text-sm text-stone-500 line-clamp-2">{[o.items?.top,o.items?.bottom,o.items?.shoes].filter(Boolean).join(' · ')}</p></button>)}</div><div className="rounded-2xl bg-emerald-50 border border-emerald-100 p-4 mb-6"><p className="text-xs text-emerald-800 font-medium mb-2">Also for you</p><div className="space-y-1 text-sm text-stone-700">{data.hairstyleSuggestion&&<p>Hair — {data.hairstyleSuggestion}</p>}{data.eyewearSuggestion&&<p>Eyewear — {data.eyewearSuggestion}</p>}{data.accessorySuggestion&&<p>Accessories — {data.accessorySuggestion}</p>}</div></div><GhostButton className="w-full" onClick={onAnother}>Try another look</GhostButton></div> }
export function DetailScreen({outfit,onBack,onAnother}) { return <div><p className="text-xs text-emerald-700 mb-1">Full outfit</p><h2 className="font-display text-2xl mb-4">{outfit.title}</h2><div className="rounded-3xl border border-stone-200 bg-white p-5 mb-4"><ItemRow label="Top" value={outfit.items?.top}/><ItemRow label="Bottom" value={outfit.items?.bottom}/><ItemRow label="Outerwear" value={outfit.items?.outerwear}/><ItemRow label="Shoes" value={outfit.items?.shoes}/><ItemRow label="Watch" value={outfit.items?.watch}/><ItemRow label="Eyewear" value={outfit.items?.eyewear}/><ItemRow label="Accessory" value={outfit.items?.accessory}/></div><div className="rounded-2xl border border-stone-200 p-4 mb-4"><p className="text-xs text-stone-400 mb-1.5">Why this works for you</p><p className="text-sm text-stone-700 leading-relaxed">{outfit.why}</p></div>{outfit.colorNotes&&<div className="rounded-2xl border border-stone-200 p-4 mb-6"><p className="text-xs text-stone-400 mb-1.5">Color notes</p><p className="text-sm text-stone-700 leading-relaxed">{outfit.colorNotes}</p></div>}<div className="flex gap-3"><GhostButton className="flex-1" onClick={onBack}>Back to looks</GhostButton><PrimaryButton className="flex-1" onClick={onAnother}>Try another look</PrimaryButton></div></div> }
