import React from 'react'
export function Spinner({label}) {
  return <div className="flex flex-col items-center justify-center gap-4 py-16"><div className="relative w-14 h-14"><div className="absolute inset-0 rounded-full border-2 border-stone-300"/><div className="absolute inset-0 rounded-full border-2 border-transparent border-t-emerald-700 animate-spin"/></div><p className="text-stone-500 text-sm tracking-wide">{label}</p></div>
}
const COLOR_MAP={navy:'#26344A',olive:'#5C5F3C',cream:'#EDE6D6',burgundy:'#6E2A32',charcoal:'#3A3A3E',beige:'#D9C9A8',black:'#1B1B1D',white:'#F6F4EF',rust:'#9C5230',sage:'#8A9678',stone:'#B9AE9B',denim:'#4C6178',brown:'#5A4130',tan:'#C9AE83',grey:'#8A8A85',gray:'#8A8A85'}
export function ColorSwatch({name}) { const hex=COLOR_MAP[(name||'').toLowerCase().trim()]||'#A9A49A'; return <span className="inline-flex items-center gap-1.5 rounded-full border border-stone-300 bg-white pl-1.5 pr-3 py-1 text-xs text-stone-800"><span className="w-3.5 h-3.5 rounded-full border border-black/10" style={{background:hex}}/>{name}</span> }
export function Pill({selected,onClick,children}) { return <button onClick={onClick} className={'px-4 py-2.5 rounded-full text-sm border transition-colors '+(selected?'bg-emerald-700 border-emerald-700 text-white':'bg-white border-stone-300 text-stone-700 hover:border-emerald-400')}>{children}</button> }
export function PrimaryButton({children,className='',...props}) { return <button className={'rounded-full bg-emerald-700 text-white font-medium px-7 py-3.5 disabled:opacity-35 disabled:cursor-not-allowed hover:bg-emerald-800 transition-colors '+className} {...props}>{children}</button> }
export function GhostButton({children,className='',...props}) { return <button className={'rounded-full border border-stone-300 text-stone-700 font-medium px-6 py-3 hover:border-emerald-400 transition-colors '+className} {...props}>{children}</button> }
export function ItemRow({label,value}) { if(!value)return null; return <div className="flex justify-between text-sm py-1.5 border-b border-stone-100 last:border-0"><span className="text-stone-400">{label}</span><span className="text-stone-800 text-right max-w-[65%]">{value}</span></div> }
